name: testing

on:
    push:
    pull_request:

env:
    RENV_PATHS_ROOT: ~/.cache/R/renv

jobs:
    caching:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4

            - name: Installing R
              uses: r-lib/actions/setup-r@v2
              with:
                r-version: 'renv'

            - name: Install and activate renv
              run: |
                install.packages("renv")
                renv::activate()
              shell: Rscript {0}

            - name: Cache packages
              uses: actions/cache@v4
              with:
                path: ${{ env.RENV_PATHS_ROOT }}
                key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
                restore-keys: |
                  ${{ runner.os }}-renv-

    restoring:
        runs-on: ubuntu-latest
        needs: caching

        steps:

            - uses: actions/checkout@v4

            - name: Installing R
              uses: r-lib/actions/setup-r@v2

            - name: Cache packages
              uses: actions/cache@v4
              with:
                path: ${{ env.RENV_PATHS_ROOT }}
                key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
                restore-keys: |
                  ${{ runner.os }}-renv-

            - name: Restore packages
              shell: Rscript {0}
              run: |
                if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
                renv::restore()

            - run: |
                library(slurmR)
                whoami()
              shell: Rscript {0}

            
            